[env]
framework = arduino

[env:esp8266_d1_mini]
platform = espressif8266
board = d1_mini
monitor_speed = 74880
platform_packages =
    framework-arduinoespressif8266 @ 3.30102.0

[env:esp32_devkit]
platform = espressif32
board = esp32dev
monitor_speed = 115200
