#!/usr/bin/env python3
"""Generate src/http/qymera_dashboard_html.h from src/http/dashboard.html.

The firmware embeds the Dashboard UI as a C string constant. This script is
the only place that transforms HTML/JS into the C literal, so the UI source
can stay readable and correctly escaped.

Usage:
    python tools/gen_dashboard_html.py   # writes qymera_dashboard_html.h

The generated header is committed; no build step depends on this script.
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "..", "src", "http", "dashboard.html")
DST = os.path.join(HERE, "..", "src", "http", "qymera_dashboard_html.h")


def c_escape_char(c):
    if c == '"':
        return '\\"'
    if c == "\\":
        return "\\\\"
    if c == "\n":
        return "\\n"
    if c == "\t":
        return "\\t"
    return c


def main():
    with open(SRC, "r", encoding="utf-8") as f:
        text = f.read()
    # Keep one string-literal fragment per source line for debuggable output.
    lines = []
    html_lines = text.split("\n")
    for i, raw in enumerate(html_lines):
        escaped = "".join(c_escape_char(c) for c in raw)
        lines.append('"%s\\n"' % escaped)
    body = "\n".join(lines)
    header = (
        "/* Generated by tools/gen_dashboard_html.py from src/http/dashboard.html.\n"
        " * Do not edit by hand; regenerate instead.\n"
        " */\n"
        "#pragma once\n\n"
        "static const char DASHBOARD_HTML[] =\n" + body + ";\n"
    )
    with open(DST, "w", encoding="utf-8") as f:
        f.write(header)
    print("wrote %s (%d bytes html -> %d bytes header)"
          % (DST, len(text), len(header)))


if __name__ == "__main__":
    main()